/**
 * The provenance header, and the one rule it makes sufficient.
 *
 * Three fields and no more: tool version, contract path, content hash. A run id would point
 * into a directory that gets swept, and git already knows the date.
 *
 * The rule is one sentence: write only to a path that is empty or carries a matching header.
 * A changed hash means a human edited the file; no header at all means a human wrote it. Both
 * refuse, through one code path.
 */
import { createHash } from "node:crypto";

export interface Provenance {
  toolVersion: string;
  contractPath: string;
  hash: string;
  /** Set when the run did not end green. An assist leaves its spec in the working tree. */
  notGreen?: boolean;
}

const HASH_LINE = /^ \* c8y-cygen-hash: ([0-9a-f]{64})( {2}NOT GREEN)?$/m;
const FROM_LINE = /^ \* Generated by c8y-cygen (\S+) from (.+)$/m;

export function hashBody(body: string): string {
  return createHash("sha256").update(body, "utf8").digest("hex");
}

export function renderHeader(p: Omit<Provenance, "hash">, body: string): string {
  const mark = p.notGreen ? "  NOT GREEN" : "";
  return [
    "/**",
    ` * Generated by c8y-cygen ${p.toolVersion} from ${p.contractPath}`,
    ` * c8y-cygen-hash: ${hashBody(body)}${mark}`,
    " *",
    " * Re-generated from the contract above. Edit the contract, not this file - a hand-edit",
    " * changes the hash, and the next run refuses to overwrite rather than destroying it.",
    " */",
    "",
  ].join("\n");
}

export function withHeader(p: Omit<Provenance, "hash">, body: string): string {
  return renderHeader(p, body) + body;
}

/** Splits a file into its header fields and the body the hash covers. */
export function readProvenance(
  content: string
): { provenance: Provenance; body: string } | null {
  if (!content.startsWith("/**")) return null;
  const end = content.indexOf(" */");
  if (end === -1) return null;
  const header = content.slice(0, end + 3);
  const hashMatch = HASH_LINE.exec(header);
  const fromMatch = FROM_LINE.exec(header);
  if (!hashMatch || !fromMatch) return null;

  // The header ends with " */\n"; the body is everything after it.
  const body = content.slice(end + 4);
  return {
    provenance: {
      toolVersion: fromMatch[1] as string,
      contractPath: fromMatch[2] as string,
      hash: hashMatch[1] as string,
      ...(hashMatch[2] ? { notGreen: true } : {}),
    },
    body,
  };
}

export type WriteVerdict =
  | { allowed: true; reason: "empty" | "matching-header" }
  | { allowed: false; reason: "hand-written" | "hand-edited"; detail: string };

/**
 * The whole collision policy. It covers a re-run, a hand-written file that happens to share the
 * name, and a generated file somebody fixed by hand - and it refuses the last one rather than
 * silently destroying the fix.
 */
export function mayWrite(existingContent: string | null): WriteVerdict {
  if (existingContent === null || existingContent.trim() === "") {
    return { allowed: true, reason: "empty" };
  }
  const parsed = readProvenance(existingContent);
  if (!parsed) {
    return {
      allowed: false,
      reason: "hand-written",
      detail:
        "the file carries no c8y-cygen provenance header, so a human wrote it and this run would destroy their work",
    };
  }
  if (hashBody(parsed.body) !== parsed.provenance.hash) {
    return {
      allowed: false,
      reason: "hand-edited",
      detail:
        "the content hash does not match the header, so the generated file has been edited by hand since it was written",
    };
  }
  return { allowed: true, reason: "matching-header" };
}
